import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'
import { join, resolve } from 'path'
import { CLIOptions } from './types'
import { writeConfigFiles, loadConfigFromFile, getFileStats } from './utils'
import { validateConfig } from './generators'